name: linter-checks-code

on: push

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: make install
      - uses: chekalsky/phpcs-action@v1
      - name: Run linter
        run: make lint