name: lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup phpcs
        uses: squizlabs/php_codesniffer
      - name: Run linter
        run: make lint